Mvanzulli/350
ONSAS/ONSAS.m pull request #360
Opened 2021-11-27 20:31 UTC by mvanzulli

This close #354

2021-11-27 23:23 UTC, jorgepz commented on src/assembler.m
> +                                                           nextTime )
no entiendo porque es necesario poner como argumento nexttime acá... en general esto no tiene porque ser el tiempo siguiente... puede ser el actual... la función assembler es general... ensambla cosas, vectores... le es indiferente de a qué tiempo corresponda...  sugiero pensar otro nombre para la variable

2021-11-27 23:25 UTC, jorgepz requested changes
hacer cambios en assembler

2021-11-28 02:16 UTC, mvanzulli commented on src/assembler.m
> +                                                           nextTime )
Ah okay, yo lo hice pensando en el tiempo siguiente por N-R pero estrictamente depende del método (para HHT supongo que necesitaremos de ambos tiempos). Ese cálculo es realizable pues tenemos el `analysisSettings` que se le puede extraer el `deltaT`. 

Estrictamente esa función `assembler.m` hasta entonces solo ensambla matrices tangentes y fuerzas internas o viscosas (magnitudes que dependen de las propiedades y el estado actual cinemático del modelo). No obstante no se usaba para ensamblar fuerzas externas porque estas no dependían al mismo tiempo del estado cinemático del modelo, propiedades y tiempo. Le podemos cambiar el nombre de la variable pero si no vería mal que en algún futuro exista un módulo que se dedique al ensamblaje de todo cualquier matriz, fuerzas y que en el caso general este ensamblaje dependa del tiempo, modelo y estado cinemático. ¿Qué opinas?

También acepto sugerencias para hacerle llegar el tiempo a la función aero de alguna otra manera, estrictamente ahí adentro esta el campo de viento que es quien demanda el tiempo.

2021-11-28 03:27 UTC, jorgepz commented on src/assembler.m
> +                                                           nextTime )
El cambio que sugiero es que en toda la función se use algo como time en lugar de nexttime.

2021-11-29 13:10 UTC, mvanzulli commented on src/assembler.m
> +                                                           nextTime )
Done, i misunderstood your suggestion.

2021-11-29 13:13 UTC, jorgepz approved these changes

2021-11-29 13:51 UTC, merged